/**
 * Created by michael on 11.08.17.
 */
export const ADD_USER = "ADD_USER";
export const REMOVE_USER = "REMOVE_USER";

export const PASSENGER = "PASSENGER";
export const DRIVER = "DRIVER";

//LOGIN
export const USERNAME_FILL_LOGIN = "USERNAME_FILL_LOGIN";
export const PASSWORD_FILL_LOGIN = "PASSWORD_FILL_LOGIN";
export const LOGIN_PRESS = "LOGIN_PRESS";
export const LOGOUT_PRESS = "LOGOUT_PRESS";

//PASSENGER REGISTRATION
export const USERNAME_FILL_PASSENGER = "USERNAME_FILL_PASSENGER";
export const PASSWORD_FILL_PASSENGER = "PASSWORD_FILL_PASSENGER";
export const NAME_FILL_PASSENGER = "NAME_FILL_PASSENGER";
export const PHONE_FILL_PASSENGER = "PHONE_FILL_PASSENGER";

//DRIVER REGISTRATION
export const USERNAME_FILL_DRIVER = "USERNAME_FILL_DRIVER";
export const PASSWORD_FILL_DRIVER = "PASSWORD_FILL_DRIVER";
export const NAME_FILL_DRIVER = "NAME_FILL_DRIVER";
export const PHONE_FILL_DRIVER = "PHONE_FILL_DRIVER";
export const CAR_FILL_DRIVER = "CAR_FILL_DRIVER";
export const LICENSENO_FILL_DRIVER = "LICENSENO_FILL_DRIVER";
export const CARCLASS_CHANGE_DRIVER = "CARCLASS_CHANGE_DRIVER";

//ORDER FORM
export const NAME_FILL_ORDER = "NAME_FILL_ORDER";
export const FROM_FILL_ORDER = "FROM_FILL_ORDER";
export const TO_FILL_ORDER = "TO_FILL_ORDER";
export const PHONE_FILL_ORDER = "PHONE_FILL_ORDER";
export const CARCLASS_CHANGE_ORDER = "CARCLASS_CHANGE_ORDER";
export const CREATE_ORDER = "CREATE_ORDER";